// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

public final class DataServiceProto {
  private DataServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_ChatHistoryProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_ChatHistoryProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_StockPriceProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_StockPriceProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_PriceChangeInfoProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_PriceChangeInfoProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_ScheduleEventProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_ScheduleEventProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_UserPreferenceProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_UserPreferenceProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_SaveChatHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_SaveChatHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_SaveChatHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_SaveChatHistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_GetRecentChatHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_GetRecentChatHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_GetRecentChatHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_GetRecentChatHistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_GetChatHistoryBySessionIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_GetChatHistoryBySessionIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_GetChatHistoryBySessionIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_GetChatHistoryBySessionIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_ExtractKeyInfoFromContextRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_ExtractKeyInfoFromContextRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_ExtractKeyInfoFromContextResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_ExtractKeyInfoFromContextResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_SaveStockPriceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_SaveStockPriceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_SaveStockPriceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_SaveStockPriceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_GetRecentStockPriceBySymbolRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_GetRecentStockPriceBySymbolRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_GetRecentStockPriceBySymbolResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_GetRecentStockPriceBySymbolResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_SavePriceChangeInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_SavePriceChangeInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_SavePriceChangeInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_SavePriceChangeInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_GetRecentPriceChangeInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_GetRecentPriceChangeInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_GetRecentPriceChangeInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_GetRecentPriceChangeInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_SaveScheduleEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_SaveScheduleEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_SaveScheduleEventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_SaveScheduleEventResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_GetAllActiveScheduleEventsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_GetAllActiveScheduleEventsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_GetAllActiveScheduleEventsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_GetAllActiveScheduleEventsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_UpdateScheduleEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_UpdateScheduleEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_UpdateScheduleEventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_UpdateScheduleEventResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_DeleteScheduleEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_DeleteScheduleEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_DeleteScheduleEventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_DeleteScheduleEventResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_SaveUserPreferenceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_SaveUserPreferenceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_SaveUserPreferenceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_SaveUserPreferenceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_GetUserPreferencesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_GetUserPreferencesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_GetUserPreferencesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_GetUserPreferencesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_DeleteUserPreferenceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_DeleteUserPreferenceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_skyeai_jarvis_DeleteUserPreferenceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_skyeai_jarvis_DeleteUserPreferenceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022data_service.proto\022\021com.skyeai.jarvis\"" +
      "v\n\020ChatHistoryProto\022\n\n\002id\030\001 \001(\003\022\017\n\007user_" +
      "id\030\002 \001(\t\022\017\n\007content\030\003 \001(\t\022\014\n\004role\030\004 \001(\t\022" +
      "\022\n\ncreated_at\030\005 \001(\t\022\022\n\nsession_id\030\006 \001(\t\"" +
      "m\n\017StockPriceProto\022\n\n\002id\030\001 \001(\003\022\024\n\014stock_" +
      "symbol\030\002 \001(\t\022\r\n\005price\030\003 \001(\001\022\021\n\ttimestamp" +
      "\030\004 \001(\t\022\026\n\016previous_price\030\005 \001(\001\"\343\001\n\024Price" +
      "ChangeInfoProto\022\n\n\002id\030\001 \001(\003\022\024\n\014stock_sym" +
      "bol\030\002 \001(\t\022\025\n\rcurrent_price\030\003 \001(\001\022\026\n\016prev" +
      "ious_price\030\004 \001(\001\022\026\n\016change_percent\030\005 \001(\001" +
      "\022\035\n\025is_significant_change\030\006 \001(\010\022\030\n\020chang" +
      "e_direction\030\007 \001(\t\022\026\n\016recommendation\030\010 \001(" +
      "\t\022\021\n\ttimestamp\030\t \001(\t\"\340\001\n\022ScheduleEventPr" +
      "oto\022\n\n\002id\030\001 \001(\003\022\r\n\005title\030\002 \001(\t\022\021\n\tdate_t" +
      "ime\030\003 \001(\t\022\023\n\013description\030\004 \001(\t\022\022\n\ncreate" +
      "d_at\030\005 \001(\t\022\023\n\013repeat_type\030\006 \001(\t\022\025\n\rstock" +
      "_symbols\030\007 \001(\t\022\036\n\026price_change_threshold" +
      "\030\010 \001(\001\022\016\n\006active\030\t \001(\010\022\027\n\017last_check_tim" +
      "e\030\n \001(\t\"\254\001\n\023UserPreferenceProto\022\n\n\002id\030\001 " +
      "\001(\003\022\017\n\007user_id\030\002 \001(\t\022\026\n\016preference_key\030\003" +
      " \001(\t\022\r\n\005value\030\004 \001(\t\022\022\n\ncreated_at\030\005 \001(\t\022" +
      "\022\n\nupdated_at\030\006 \001(\t\022\027\n\017preference_type\030\007" +
      " \001(\t\022\020\n\010priority\030\010 \001(\005\"\\\n\026SaveChatHistor" +
      "yRequest\022\017\n\007user_id\030\001 \001(\t\022\017\n\007content\030\002 \001" +
      "(\t\022\014\n\004role\030\003 \001(\t\022\022\n\nsession_id\030\004 \001(\t\"T\n\027" +
      "SaveChatHistoryResponse\0229\n\014chat_history\030" +
      "\001 \001(\0132#.com.skyeai.jarvis.ChatHistoryPro" +
      "to\".\n\033GetRecentChatHistoryRequest\022\017\n\007use" +
      "r_id\030\001 \001(\t\"[\n\034GetRecentChatHistoryRespon" +
      "se\022;\n\016chat_histories\030\001 \003(\0132#.com.skyeai." +
      "jarvis.ChatHistoryProto\"6\n GetChatHistor" +
      "yBySessionIdRequest\022\022\n\nsession_id\030\001 \001(\t\"" +
      "`\n!GetChatHistoryBySessionIdResponse\022;\n\016" +
      "chat_histories\030\001 \003(\0132#.com.skyeai.jarvis" +
      ".ChatHistoryProto\"3\n ExtractKeyInfoFromC" +
      "ontextRequest\022\017\n\007user_id\030\001 \001(\t\"5\n!Extrac" +
      "tKeyInfoFromContextResponse\022\020\n\010key_info\030" +
      "\001 \001(\t\"P\n\025SaveStockPriceRequest\0227\n\013stock_" +
      "price\030\001 \001(\0132\".com.skyeai.jarvis.StockPri" +
      "ceProto\"Q\n\026SaveStockPriceResponse\0227\n\013sto" +
      "ck_price\030\001 \001(\0132\".com.skyeai.jarvis.Stock" +
      "PriceProto\":\n\"GetRecentStockPriceBySymbo" +
      "lRequest\022\024\n\014stock_symbol\030\001 \001(\t\"^\n#GetRec" +
      "entStockPriceBySymbolResponse\0227\n\013stock_p" +
      "rice\030\001 \001(\0132\".com.skyeai.jarvis.StockPric" +
      "eProto\"`\n\032SavePriceChangeInfoRequest\022B\n\021" +
      "price_change_info\030\001 \001(\0132\'.com.skyeai.jar" +
      "vis.PriceChangeInfoProto\"a\n\033SavePriceCha" +
      "ngeInfoResponse\022B\n\021price_change_info\030\001 \001" +
      "(\0132\'.com.skyeai.jarvis.PriceChangeInfoPr" +
      "oto\"F\n\037GetRecentPriceChangeInfoRequest\022\024" +
      "\n\014stock_symbol\030\001 \001(\t\022\r\n\005limit\030\002 \001(\005\"g\n G" +
      "etRecentPriceChangeInfoResponse\022C\n\022price" +
      "_change_infos\030\001 \003(\0132\'.com.skyeai.jarvis." +
      "PriceChangeInfoProto\"Y\n\030SaveScheduleEven" +
      "tRequest\022=\n\016schedule_event\030\001 \001(\0132%.com.s" +
      "kyeai.jarvis.ScheduleEventProto\"Z\n\031SaveS" +
      "cheduleEventResponse\022=\n\016schedule_event\030\001" +
      " \001(\0132%.com.skyeai.jarvis.ScheduleEventPr" +
      "oto\"#\n!GetAllActiveScheduleEventsRequest" +
      "\"d\n\"GetAllActiveScheduleEventsResponse\022>" +
      "\n\017schedule_events\030\001 \003(\0132%.com.skyeai.jar" +
      "vis.ScheduleEventProto\"[\n\032UpdateSchedule" +
      "EventRequest\022=\n\016schedule_event\030\001 \001(\0132%.c" +
      "om.skyeai.jarvis.ScheduleEventProto\".\n\033U" +
      "pdateScheduleEventResponse\022\017\n\007success\030\001 " +
      "\001(\010\"(\n\032DeleteScheduleEventRequest\022\n\n\002id\030" +
      "\001 \001(\003\".\n\033DeleteScheduleEventResponse\022\017\n\007" +
      "success\030\001 \001(\010\"~\n\031SaveUserPreferenceReque" +
      "st\022\017\n\007user_id\030\001 \001(\t\022\026\n\016preference_key\030\002 " +
      "\001(\t\022\r\n\005value\030\003 \001(\t\022\027\n\017preference_type\030\004 " +
      "\001(\t\022\020\n\010priority\030\005 \001(\005\"]\n\032SaveUserPrefere" +
      "nceResponse\022?\n\017user_preference\030\001 \001(\0132&.c" +
      "om.skyeai.jarvis.UserPreferenceProto\"D\n\031" +
      "GetUserPreferencesRequest\022\017\n\007user_id\030\001 \001" +
      "(\t\022\026\n\016preference_key\030\002 \001(\t\"^\n\032GetUserPre" +
      "ferencesResponse\022@\n\020user_preferences\030\001 \003" +
      "(\0132&.com.skyeai.jarvis.UserPreferencePro" +
      "to\"F\n\033DeleteUserPreferenceRequest\022\017\n\007use" +
      "r_id\030\001 \001(\t\022\026\n\016preference_key\030\002 \001(\t\"/\n\034De" +
      "leteUserPreferenceResponse\022\017\n\007success\030\001 " +
      "\001(\0102\273\016\n\013DataService\022h\n\017SaveChatHistory\022)" +
      ".com.skyeai.jarvis.SaveChatHistoryReques" +
      "t\032*.com.skyeai.jarvis.SaveChatHistoryRes" +
      "ponse\022w\n\024GetRecentChatHistory\022..com.skye" +
      "ai.jarvis.GetRecentChatHistoryRequest\032/." +
      "com.skyeai.jarvis.GetRecentChatHistoryRe" +
      "sponse\022\206\001\n\031GetChatHistoryBySessionId\0223.c" +
      "om.skyeai.jarvis.GetChatHistoryBySession" +
      "IdRequest\0324.com.skyeai.jarvis.GetChatHis" +
      "toryBySessionIdResponse\022\206\001\n\031ExtractKeyIn" +
      "foFromContext\0223.com.skyeai.jarvis.Extrac" +
      "tKeyInfoFromContextRequest\0324.com.skyeai." +
      "jarvis.ExtractKeyInfoFromContextResponse" +
      "\022e\n\016SaveStockPrice\022(.com.skyeai.jarvis.S" +
      "aveStockPriceRequest\032).com.skyeai.jarvis" +
      ".SaveStockPriceResponse\022\214\001\n\033GetRecentSto" +
      "ckPriceBySymbol\0225.com.skyeai.jarvis.GetR" +
      "ecentStockPriceBySymbolRequest\0326.com.sky" +
      "eai.jarvis.GetRecentStockPriceBySymbolRe" +
      "sponse\022t\n\023SavePriceChangeInfo\022-.com.skye" +
      "ai.jarvis.SavePriceChangeInfoRequest\032..c" +
      "om.skyeai.jarvis.SavePriceChangeInfoResp" +
      "onse\022\203\001\n\030GetRecentPriceChangeInfo\0222.com." +
      "skyeai.jarvis.GetRecentPriceChangeInfoRe" +
      "quest\0323.com.skyeai.jarvis.GetRecentPrice" +
      "ChangeInfoResponse\022n\n\021SaveScheduleEvent\022" +
      "+.com.skyeai.jarvis.SaveScheduleEventReq" +
      "uest\032,.com.skyeai.jarvis.SaveScheduleEve" +
      "ntResponse\022\211\001\n\032GetAllActiveScheduleEvent" +
      "s\0224.com.skyeai.jarvis.GetAllActiveSchedu" +
      "leEventsRequest\0325.com.skyeai.jarvis.GetA" +
      "llActiveScheduleEventsResponse\022t\n\023Update" +
      "ScheduleEvent\022-.com.skyeai.jarvis.Update" +
      "ScheduleEventRequest\032..com.skyeai.jarvis" +
      ".UpdateScheduleEventResponse\022t\n\023DeleteSc" +
      "heduleEvent\022-.com.skyeai.jarvis.DeleteSc" +
      "heduleEventRequest\032..com.skyeai.jarvis.D" +
      "eleteScheduleEventResponse\022q\n\022SaveUserPr" +
      "eference\022,.com.skyeai.jarvis.SaveUserPre" +
      "ferenceRequest\032-.com.skyeai.jarvis.SaveU" +
      "serPreferenceResponse\022q\n\022GetUserPreferen" +
      "ces\022,.com.skyeai.jarvis.GetUserPreferenc" +
      "esRequest\032-.com.skyeai.jarvis.GetUserPre" +
      "ferencesResponse\022w\n\024DeleteUserPreference" +
      "\022..com.skyeai.jarvis.DeleteUserPreferenc" +
      "eRequest\032/.com.skyeai.jarvis.DeleteUserP" +
      "referenceResponseB0\n\032com.skyeai.jarvis.p" +
      "rotobufB\020DataServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_skyeai_jarvis_ChatHistoryProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_skyeai_jarvis_ChatHistoryProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_ChatHistoryProto_descriptor,
        new java.lang.String[] { "Id", "UserId", "Content", "Role", "CreatedAt", "SessionId", });
    internal_static_com_skyeai_jarvis_StockPriceProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_skyeai_jarvis_StockPriceProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_StockPriceProto_descriptor,
        new java.lang.String[] { "Id", "StockSymbol", "Price", "Timestamp", "PreviousPrice", });
    internal_static_com_skyeai_jarvis_PriceChangeInfoProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_skyeai_jarvis_PriceChangeInfoProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_PriceChangeInfoProto_descriptor,
        new java.lang.String[] { "Id", "StockSymbol", "CurrentPrice", "PreviousPrice", "ChangePercent", "IsSignificantChange", "ChangeDirection", "Recommendation", "Timestamp", });
    internal_static_com_skyeai_jarvis_ScheduleEventProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_skyeai_jarvis_ScheduleEventProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_ScheduleEventProto_descriptor,
        new java.lang.String[] { "Id", "Title", "DateTime", "Description", "CreatedAt", "RepeatType", "StockSymbols", "PriceChangeThreshold", "Active", "LastCheckTime", });
    internal_static_com_skyeai_jarvis_UserPreferenceProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_skyeai_jarvis_UserPreferenceProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_UserPreferenceProto_descriptor,
        new java.lang.String[] { "Id", "UserId", "PreferenceKey", "Value", "CreatedAt", "UpdatedAt", "PreferenceType", "Priority", });
    internal_static_com_skyeai_jarvis_SaveChatHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_skyeai_jarvis_SaveChatHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_SaveChatHistoryRequest_descriptor,
        new java.lang.String[] { "UserId", "Content", "Role", "SessionId", });
    internal_static_com_skyeai_jarvis_SaveChatHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_skyeai_jarvis_SaveChatHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_SaveChatHistoryResponse_descriptor,
        new java.lang.String[] { "ChatHistory", });
    internal_static_com_skyeai_jarvis_GetRecentChatHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_skyeai_jarvis_GetRecentChatHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_GetRecentChatHistoryRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_com_skyeai_jarvis_GetRecentChatHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_skyeai_jarvis_GetRecentChatHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_GetRecentChatHistoryResponse_descriptor,
        new java.lang.String[] { "ChatHistories", });
    internal_static_com_skyeai_jarvis_GetChatHistoryBySessionIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_skyeai_jarvis_GetChatHistoryBySessionIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_GetChatHistoryBySessionIdRequest_descriptor,
        new java.lang.String[] { "SessionId", });
    internal_static_com_skyeai_jarvis_GetChatHistoryBySessionIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_skyeai_jarvis_GetChatHistoryBySessionIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_GetChatHistoryBySessionIdResponse_descriptor,
        new java.lang.String[] { "ChatHistories", });
    internal_static_com_skyeai_jarvis_ExtractKeyInfoFromContextRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_skyeai_jarvis_ExtractKeyInfoFromContextRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_ExtractKeyInfoFromContextRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_com_skyeai_jarvis_ExtractKeyInfoFromContextResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_skyeai_jarvis_ExtractKeyInfoFromContextResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_ExtractKeyInfoFromContextResponse_descriptor,
        new java.lang.String[] { "KeyInfo", });
    internal_static_com_skyeai_jarvis_SaveStockPriceRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_skyeai_jarvis_SaveStockPriceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_SaveStockPriceRequest_descriptor,
        new java.lang.String[] { "StockPrice", });
    internal_static_com_skyeai_jarvis_SaveStockPriceResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_skyeai_jarvis_SaveStockPriceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_SaveStockPriceResponse_descriptor,
        new java.lang.String[] { "StockPrice", });
    internal_static_com_skyeai_jarvis_GetRecentStockPriceBySymbolRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_skyeai_jarvis_GetRecentStockPriceBySymbolRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_GetRecentStockPriceBySymbolRequest_descriptor,
        new java.lang.String[] { "StockSymbol", });
    internal_static_com_skyeai_jarvis_GetRecentStockPriceBySymbolResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_skyeai_jarvis_GetRecentStockPriceBySymbolResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_GetRecentStockPriceBySymbolResponse_descriptor,
        new java.lang.String[] { "StockPrice", });
    internal_static_com_skyeai_jarvis_SavePriceChangeInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_skyeai_jarvis_SavePriceChangeInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_SavePriceChangeInfoRequest_descriptor,
        new java.lang.String[] { "PriceChangeInfo", });
    internal_static_com_skyeai_jarvis_SavePriceChangeInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_skyeai_jarvis_SavePriceChangeInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_SavePriceChangeInfoResponse_descriptor,
        new java.lang.String[] { "PriceChangeInfo", });
    internal_static_com_skyeai_jarvis_GetRecentPriceChangeInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_skyeai_jarvis_GetRecentPriceChangeInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_GetRecentPriceChangeInfoRequest_descriptor,
        new java.lang.String[] { "StockSymbol", "Limit", });
    internal_static_com_skyeai_jarvis_GetRecentPriceChangeInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_skyeai_jarvis_GetRecentPriceChangeInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_GetRecentPriceChangeInfoResponse_descriptor,
        new java.lang.String[] { "PriceChangeInfos", });
    internal_static_com_skyeai_jarvis_SaveScheduleEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_skyeai_jarvis_SaveScheduleEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_SaveScheduleEventRequest_descriptor,
        new java.lang.String[] { "ScheduleEvent", });
    internal_static_com_skyeai_jarvis_SaveScheduleEventResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_com_skyeai_jarvis_SaveScheduleEventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_SaveScheduleEventResponse_descriptor,
        new java.lang.String[] { "ScheduleEvent", });
    internal_static_com_skyeai_jarvis_GetAllActiveScheduleEventsRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_com_skyeai_jarvis_GetAllActiveScheduleEventsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_GetAllActiveScheduleEventsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_skyeai_jarvis_GetAllActiveScheduleEventsResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_com_skyeai_jarvis_GetAllActiveScheduleEventsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_GetAllActiveScheduleEventsResponse_descriptor,
        new java.lang.String[] { "ScheduleEvents", });
    internal_static_com_skyeai_jarvis_UpdateScheduleEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_com_skyeai_jarvis_UpdateScheduleEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_UpdateScheduleEventRequest_descriptor,
        new java.lang.String[] { "ScheduleEvent", });
    internal_static_com_skyeai_jarvis_UpdateScheduleEventResponse_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_com_skyeai_jarvis_UpdateScheduleEventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_UpdateScheduleEventResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_com_skyeai_jarvis_DeleteScheduleEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_com_skyeai_jarvis_DeleteScheduleEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_DeleteScheduleEventRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_skyeai_jarvis_DeleteScheduleEventResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_com_skyeai_jarvis_DeleteScheduleEventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_DeleteScheduleEventResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_com_skyeai_jarvis_SaveUserPreferenceRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_com_skyeai_jarvis_SaveUserPreferenceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_SaveUserPreferenceRequest_descriptor,
        new java.lang.String[] { "UserId", "PreferenceKey", "Value", "PreferenceType", "Priority", });
    internal_static_com_skyeai_jarvis_SaveUserPreferenceResponse_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_com_skyeai_jarvis_SaveUserPreferenceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_SaveUserPreferenceResponse_descriptor,
        new java.lang.String[] { "UserPreference", });
    internal_static_com_skyeai_jarvis_GetUserPreferencesRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_com_skyeai_jarvis_GetUserPreferencesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_GetUserPreferencesRequest_descriptor,
        new java.lang.String[] { "UserId", "PreferenceKey", });
    internal_static_com_skyeai_jarvis_GetUserPreferencesResponse_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_com_skyeai_jarvis_GetUserPreferencesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_GetUserPreferencesResponse_descriptor,
        new java.lang.String[] { "UserPreferences", });
    internal_static_com_skyeai_jarvis_DeleteUserPreferenceRequest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_com_skyeai_jarvis_DeleteUserPreferenceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_DeleteUserPreferenceRequest_descriptor,
        new java.lang.String[] { "UserId", "PreferenceKey", });
    internal_static_com_skyeai_jarvis_DeleteUserPreferenceResponse_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_com_skyeai_jarvis_DeleteUserPreferenceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_skyeai_jarvis_DeleteUserPreferenceResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
