// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

/**
 * <pre>
 * 获取用户最近聊天历史响应
 * </pre>
 *
 * Protobuf type {@code com.skyeai.jarvis.GetRecentChatHistoryResponse}
 */
public final class GetRecentChatHistoryResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.skyeai.jarvis.GetRecentChatHistoryResponse)
    GetRecentChatHistoryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetRecentChatHistoryResponse.newBuilder() to construct.
  private GetRecentChatHistoryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetRecentChatHistoryResponse() {
    chatHistories_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetRecentChatHistoryResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_GetRecentChatHistoryResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_GetRecentChatHistoryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse.class, com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse.Builder.class);
  }

  public static final int CHAT_HISTORIES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.skyeai.jarvis.protobuf.ChatHistoryProto> chatHistories_;
  /**
   * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.skyeai.jarvis.protobuf.ChatHistoryProto> getChatHistoriesList() {
    return chatHistories_;
  }
  /**
   * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.skyeai.jarvis.protobuf.ChatHistoryProtoOrBuilder> 
      getChatHistoriesOrBuilderList() {
    return chatHistories_;
  }
  /**
   * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
   */
  @java.lang.Override
  public int getChatHistoriesCount() {
    return chatHistories_.size();
  }
  /**
   * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
   */
  @java.lang.Override
  public com.skyeai.jarvis.protobuf.ChatHistoryProto getChatHistories(int index) {
    return chatHistories_.get(index);
  }
  /**
   * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
   */
  @java.lang.Override
  public com.skyeai.jarvis.protobuf.ChatHistoryProtoOrBuilder getChatHistoriesOrBuilder(
      int index) {
    return chatHistories_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < chatHistories_.size(); i++) {
      output.writeMessage(1, chatHistories_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < chatHistories_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, chatHistories_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse)) {
      return super.equals(obj);
    }
    com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse other = (com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse) obj;

    if (!getChatHistoriesList()
        .equals(other.getChatHistoriesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getChatHistoriesCount() > 0) {
      hash = (37 * hash) + CHAT_HISTORIES_FIELD_NUMBER;
      hash = (53 * hash) + getChatHistoriesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 获取用户最近聊天历史响应
   * </pre>
   *
   * Protobuf type {@code com.skyeai.jarvis.GetRecentChatHistoryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.skyeai.jarvis.GetRecentChatHistoryResponse)
      com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_GetRecentChatHistoryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_GetRecentChatHistoryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse.class, com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse.Builder.class);
    }

    // Construct using com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (chatHistoriesBuilder_ == null) {
        chatHistories_ = java.util.Collections.emptyList();
      } else {
        chatHistories_ = null;
        chatHistoriesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_GetRecentChatHistoryResponse_descriptor;
    }

    @java.lang.Override
    public com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse getDefaultInstanceForType() {
      return com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse build() {
      com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse buildPartial() {
      com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse result = new com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse result) {
      if (chatHistoriesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          chatHistories_ = java.util.Collections.unmodifiableList(chatHistories_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.chatHistories_ = chatHistories_;
      } else {
        result.chatHistories_ = chatHistoriesBuilder_.build();
      }
    }

    private void buildPartial0(com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse) {
        return mergeFrom((com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse other) {
      if (other == com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse.getDefaultInstance()) return this;
      if (chatHistoriesBuilder_ == null) {
        if (!other.chatHistories_.isEmpty()) {
          if (chatHistories_.isEmpty()) {
            chatHistories_ = other.chatHistories_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChatHistoriesIsMutable();
            chatHistories_.addAll(other.chatHistories_);
          }
          onChanged();
        }
      } else {
        if (!other.chatHistories_.isEmpty()) {
          if (chatHistoriesBuilder_.isEmpty()) {
            chatHistoriesBuilder_.dispose();
            chatHistoriesBuilder_ = null;
            chatHistories_ = other.chatHistories_;
            bitField0_ = (bitField0_ & ~0x00000001);
            chatHistoriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getChatHistoriesFieldBuilder() : null;
          } else {
            chatHistoriesBuilder_.addAllMessages(other.chatHistories_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.skyeai.jarvis.protobuf.ChatHistoryProto m =
                  input.readMessage(
                      com.skyeai.jarvis.protobuf.ChatHistoryProto.parser(),
                      extensionRegistry);
              if (chatHistoriesBuilder_ == null) {
                ensureChatHistoriesIsMutable();
                chatHistories_.add(m);
              } else {
                chatHistoriesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.skyeai.jarvis.protobuf.ChatHistoryProto> chatHistories_ =
      java.util.Collections.emptyList();
    private void ensureChatHistoriesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        chatHistories_ = new java.util.ArrayList<com.skyeai.jarvis.protobuf.ChatHistoryProto>(chatHistories_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.skyeai.jarvis.protobuf.ChatHistoryProto, com.skyeai.jarvis.protobuf.ChatHistoryProto.Builder, com.skyeai.jarvis.protobuf.ChatHistoryProtoOrBuilder> chatHistoriesBuilder_;

    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public java.util.List<com.skyeai.jarvis.protobuf.ChatHistoryProto> getChatHistoriesList() {
      if (chatHistoriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(chatHistories_);
      } else {
        return chatHistoriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public int getChatHistoriesCount() {
      if (chatHistoriesBuilder_ == null) {
        return chatHistories_.size();
      } else {
        return chatHistoriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public com.skyeai.jarvis.protobuf.ChatHistoryProto getChatHistories(int index) {
      if (chatHistoriesBuilder_ == null) {
        return chatHistories_.get(index);
      } else {
        return chatHistoriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public Builder setChatHistories(
        int index, com.skyeai.jarvis.protobuf.ChatHistoryProto value) {
      if (chatHistoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChatHistoriesIsMutable();
        chatHistories_.set(index, value);
        onChanged();
      } else {
        chatHistoriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public Builder setChatHistories(
        int index, com.skyeai.jarvis.protobuf.ChatHistoryProto.Builder builderForValue) {
      if (chatHistoriesBuilder_ == null) {
        ensureChatHistoriesIsMutable();
        chatHistories_.set(index, builderForValue.build());
        onChanged();
      } else {
        chatHistoriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public Builder addChatHistories(com.skyeai.jarvis.protobuf.ChatHistoryProto value) {
      if (chatHistoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChatHistoriesIsMutable();
        chatHistories_.add(value);
        onChanged();
      } else {
        chatHistoriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public Builder addChatHistories(
        int index, com.skyeai.jarvis.protobuf.ChatHistoryProto value) {
      if (chatHistoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChatHistoriesIsMutable();
        chatHistories_.add(index, value);
        onChanged();
      } else {
        chatHistoriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public Builder addChatHistories(
        com.skyeai.jarvis.protobuf.ChatHistoryProto.Builder builderForValue) {
      if (chatHistoriesBuilder_ == null) {
        ensureChatHistoriesIsMutable();
        chatHistories_.add(builderForValue.build());
        onChanged();
      } else {
        chatHistoriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public Builder addChatHistories(
        int index, com.skyeai.jarvis.protobuf.ChatHistoryProto.Builder builderForValue) {
      if (chatHistoriesBuilder_ == null) {
        ensureChatHistoriesIsMutable();
        chatHistories_.add(index, builderForValue.build());
        onChanged();
      } else {
        chatHistoriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public Builder addAllChatHistories(
        java.lang.Iterable<? extends com.skyeai.jarvis.protobuf.ChatHistoryProto> values) {
      if (chatHistoriesBuilder_ == null) {
        ensureChatHistoriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, chatHistories_);
        onChanged();
      } else {
        chatHistoriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public Builder clearChatHistories() {
      if (chatHistoriesBuilder_ == null) {
        chatHistories_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        chatHistoriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public Builder removeChatHistories(int index) {
      if (chatHistoriesBuilder_ == null) {
        ensureChatHistoriesIsMutable();
        chatHistories_.remove(index);
        onChanged();
      } else {
        chatHistoriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public com.skyeai.jarvis.protobuf.ChatHistoryProto.Builder getChatHistoriesBuilder(
        int index) {
      return getChatHistoriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public com.skyeai.jarvis.protobuf.ChatHistoryProtoOrBuilder getChatHistoriesOrBuilder(
        int index) {
      if (chatHistoriesBuilder_ == null) {
        return chatHistories_.get(index);  } else {
        return chatHistoriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public java.util.List<? extends com.skyeai.jarvis.protobuf.ChatHistoryProtoOrBuilder> 
         getChatHistoriesOrBuilderList() {
      if (chatHistoriesBuilder_ != null) {
        return chatHistoriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(chatHistories_);
      }
    }
    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public com.skyeai.jarvis.protobuf.ChatHistoryProto.Builder addChatHistoriesBuilder() {
      return getChatHistoriesFieldBuilder().addBuilder(
          com.skyeai.jarvis.protobuf.ChatHistoryProto.getDefaultInstance());
    }
    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public com.skyeai.jarvis.protobuf.ChatHistoryProto.Builder addChatHistoriesBuilder(
        int index) {
      return getChatHistoriesFieldBuilder().addBuilder(
          index, com.skyeai.jarvis.protobuf.ChatHistoryProto.getDefaultInstance());
    }
    /**
     * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
     */
    public java.util.List<com.skyeai.jarvis.protobuf.ChatHistoryProto.Builder> 
         getChatHistoriesBuilderList() {
      return getChatHistoriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.skyeai.jarvis.protobuf.ChatHistoryProto, com.skyeai.jarvis.protobuf.ChatHistoryProto.Builder, com.skyeai.jarvis.protobuf.ChatHistoryProtoOrBuilder> 
        getChatHistoriesFieldBuilder() {
      if (chatHistoriesBuilder_ == null) {
        chatHistoriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.skyeai.jarvis.protobuf.ChatHistoryProto, com.skyeai.jarvis.protobuf.ChatHistoryProto.Builder, com.skyeai.jarvis.protobuf.ChatHistoryProtoOrBuilder>(
                chatHistories_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        chatHistories_ = null;
      }
      return chatHistoriesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.skyeai.jarvis.GetRecentChatHistoryResponse)
  }

  // @@protoc_insertion_point(class_scope:com.skyeai.jarvis.GetRecentChatHistoryResponse)
  private static final com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse();
  }

  public static com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetRecentChatHistoryResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetRecentChatHistoryResponse>() {
    @java.lang.Override
    public GetRecentChatHistoryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetRecentChatHistoryResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetRecentChatHistoryResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.skyeai.jarvis.protobuf.GetRecentChatHistoryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

