// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

/**
 * <pre>
 * 价格变动信息消息
 * </pre>
 *
 * Protobuf type {@code com.skyeai.jarvis.PriceChangeInfoProto}
 */
public final class PriceChangeInfoProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.skyeai.jarvis.PriceChangeInfoProto)
    PriceChangeInfoProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PriceChangeInfoProto.newBuilder() to construct.
  private PriceChangeInfoProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PriceChangeInfoProto() {
    stockSymbol_ = "";
    changeDirection_ = "";
    recommendation_ = "";
    timestamp_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PriceChangeInfoProto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_PriceChangeInfoProto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_PriceChangeInfoProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.skyeai.jarvis.protobuf.PriceChangeInfoProto.class, com.skyeai.jarvis.protobuf.PriceChangeInfoProto.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int STOCK_SYMBOL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stockSymbol_ = "";
  /**
   * <code>string stock_symbol = 2;</code>
   * @return The stockSymbol.
   */
  @java.lang.Override
  public java.lang.String getStockSymbol() {
    java.lang.Object ref = stockSymbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stockSymbol_ = s;
      return s;
    }
  }
  /**
   * <code>string stock_symbol = 2;</code>
   * @return The bytes for stockSymbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStockSymbolBytes() {
    java.lang.Object ref = stockSymbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stockSymbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENT_PRICE_FIELD_NUMBER = 3;
  private double currentPrice_ = 0D;
  /**
   * <code>double current_price = 3;</code>
   * @return The currentPrice.
   */
  @java.lang.Override
  public double getCurrentPrice() {
    return currentPrice_;
  }

  public static final int PREVIOUS_PRICE_FIELD_NUMBER = 4;
  private double previousPrice_ = 0D;
  /**
   * <code>double previous_price = 4;</code>
   * @return The previousPrice.
   */
  @java.lang.Override
  public double getPreviousPrice() {
    return previousPrice_;
  }

  public static final int CHANGE_PERCENT_FIELD_NUMBER = 5;
  private double changePercent_ = 0D;
  /**
   * <code>double change_percent = 5;</code>
   * @return The changePercent.
   */
  @java.lang.Override
  public double getChangePercent() {
    return changePercent_;
  }

  public static final int IS_SIGNIFICANT_CHANGE_FIELD_NUMBER = 6;
  private boolean isSignificantChange_ = false;
  /**
   * <code>bool is_significant_change = 6;</code>
   * @return The isSignificantChange.
   */
  @java.lang.Override
  public boolean getIsSignificantChange() {
    return isSignificantChange_;
  }

  public static final int CHANGE_DIRECTION_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object changeDirection_ = "";
  /**
   * <code>string change_direction = 7;</code>
   * @return The changeDirection.
   */
  @java.lang.Override
  public java.lang.String getChangeDirection() {
    java.lang.Object ref = changeDirection_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      changeDirection_ = s;
      return s;
    }
  }
  /**
   * <code>string change_direction = 7;</code>
   * @return The bytes for changeDirection.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChangeDirectionBytes() {
    java.lang.Object ref = changeDirection_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      changeDirection_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECOMMENDATION_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object recommendation_ = "";
  /**
   * <code>string recommendation = 8;</code>
   * @return The recommendation.
   */
  @java.lang.Override
  public java.lang.String getRecommendation() {
    java.lang.Object ref = recommendation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recommendation_ = s;
      return s;
    }
  }
  /**
   * <code>string recommendation = 8;</code>
   * @return The bytes for recommendation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecommendationBytes() {
    java.lang.Object ref = recommendation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recommendation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object timestamp_ = "";
  /**
   * <pre>
   * 使用ISO 8601格式字符串
   * </pre>
   *
   * <code>string timestamp = 9;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public java.lang.String getTimestamp() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timestamp_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 使用ISO 8601格式字符串
   * </pre>
   *
   * <code>string timestamp = 9;</code>
   * @return The bytes for timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimestampBytes() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stockSymbol_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stockSymbol_);
    }
    if (java.lang.Double.doubleToRawLongBits(currentPrice_) != 0) {
      output.writeDouble(3, currentPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(previousPrice_) != 0) {
      output.writeDouble(4, previousPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(changePercent_) != 0) {
      output.writeDouble(5, changePercent_);
    }
    if (isSignificantChange_ != false) {
      output.writeBool(6, isSignificantChange_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(changeDirection_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, changeDirection_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(recommendation_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, recommendation_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestamp_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stockSymbol_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stockSymbol_);
    }
    if (java.lang.Double.doubleToRawLongBits(currentPrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, currentPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(previousPrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, previousPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(changePercent_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, changePercent_);
    }
    if (isSignificantChange_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, isSignificantChange_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(changeDirection_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, changeDirection_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(recommendation_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, recommendation_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestamp_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.skyeai.jarvis.protobuf.PriceChangeInfoProto)) {
      return super.equals(obj);
    }
    com.skyeai.jarvis.protobuf.PriceChangeInfoProto other = (com.skyeai.jarvis.protobuf.PriceChangeInfoProto) obj;

    if (getId()
        != other.getId()) return false;
    if (!getStockSymbol()
        .equals(other.getStockSymbol())) return false;
    if (java.lang.Double.doubleToLongBits(getCurrentPrice())
        != java.lang.Double.doubleToLongBits(
            other.getCurrentPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getPreviousPrice())
        != java.lang.Double.doubleToLongBits(
            other.getPreviousPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getChangePercent())
        != java.lang.Double.doubleToLongBits(
            other.getChangePercent())) return false;
    if (getIsSignificantChange()
        != other.getIsSignificantChange()) return false;
    if (!getChangeDirection()
        .equals(other.getChangeDirection())) return false;
    if (!getRecommendation()
        .equals(other.getRecommendation())) return false;
    if (!getTimestamp()
        .equals(other.getTimestamp())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + STOCK_SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getStockSymbol().hashCode();
    hash = (37 * hash) + CURRENT_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCurrentPrice()));
    hash = (37 * hash) + PREVIOUS_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPreviousPrice()));
    hash = (37 * hash) + CHANGE_PERCENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getChangePercent()));
    hash = (37 * hash) + IS_SIGNIFICANT_CHANGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSignificantChange());
    hash = (37 * hash) + CHANGE_DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + getChangeDirection().hashCode();
    hash = (37 * hash) + RECOMMENDATION_FIELD_NUMBER;
    hash = (53 * hash) + getRecommendation().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTimestamp().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.skyeai.jarvis.protobuf.PriceChangeInfoProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skyeai.jarvis.protobuf.PriceChangeInfoProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.PriceChangeInfoProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skyeai.jarvis.protobuf.PriceChangeInfoProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.PriceChangeInfoProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skyeai.jarvis.protobuf.PriceChangeInfoProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.PriceChangeInfoProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.skyeai.jarvis.protobuf.PriceChangeInfoProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.PriceChangeInfoProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.skyeai.jarvis.protobuf.PriceChangeInfoProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.PriceChangeInfoProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.skyeai.jarvis.protobuf.PriceChangeInfoProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.skyeai.jarvis.protobuf.PriceChangeInfoProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 价格变动信息消息
   * </pre>
   *
   * Protobuf type {@code com.skyeai.jarvis.PriceChangeInfoProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.skyeai.jarvis.PriceChangeInfoProto)
      com.skyeai.jarvis.protobuf.PriceChangeInfoProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_PriceChangeInfoProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_PriceChangeInfoProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skyeai.jarvis.protobuf.PriceChangeInfoProto.class, com.skyeai.jarvis.protobuf.PriceChangeInfoProto.Builder.class);
    }

    // Construct using com.skyeai.jarvis.protobuf.PriceChangeInfoProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      stockSymbol_ = "";
      currentPrice_ = 0D;
      previousPrice_ = 0D;
      changePercent_ = 0D;
      isSignificantChange_ = false;
      changeDirection_ = "";
      recommendation_ = "";
      timestamp_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_PriceChangeInfoProto_descriptor;
    }

    @java.lang.Override
    public com.skyeai.jarvis.protobuf.PriceChangeInfoProto getDefaultInstanceForType() {
      return com.skyeai.jarvis.protobuf.PriceChangeInfoProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.skyeai.jarvis.protobuf.PriceChangeInfoProto build() {
      com.skyeai.jarvis.protobuf.PriceChangeInfoProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.skyeai.jarvis.protobuf.PriceChangeInfoProto buildPartial() {
      com.skyeai.jarvis.protobuf.PriceChangeInfoProto result = new com.skyeai.jarvis.protobuf.PriceChangeInfoProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.skyeai.jarvis.protobuf.PriceChangeInfoProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.stockSymbol_ = stockSymbol_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.currentPrice_ = currentPrice_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.previousPrice_ = previousPrice_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.changePercent_ = changePercent_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.isSignificantChange_ = isSignificantChange_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.changeDirection_ = changeDirection_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.recommendation_ = recommendation_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.timestamp_ = timestamp_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.skyeai.jarvis.protobuf.PriceChangeInfoProto) {
        return mergeFrom((com.skyeai.jarvis.protobuf.PriceChangeInfoProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.skyeai.jarvis.protobuf.PriceChangeInfoProto other) {
      if (other == com.skyeai.jarvis.protobuf.PriceChangeInfoProto.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getStockSymbol().isEmpty()) {
        stockSymbol_ = other.stockSymbol_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getCurrentPrice() != 0D) {
        setCurrentPrice(other.getCurrentPrice());
      }
      if (other.getPreviousPrice() != 0D) {
        setPreviousPrice(other.getPreviousPrice());
      }
      if (other.getChangePercent() != 0D) {
        setChangePercent(other.getChangePercent());
      }
      if (other.getIsSignificantChange() != false) {
        setIsSignificantChange(other.getIsSignificantChange());
      }
      if (!other.getChangeDirection().isEmpty()) {
        changeDirection_ = other.changeDirection_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getRecommendation().isEmpty()) {
        recommendation_ = other.recommendation_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getTimestamp().isEmpty()) {
        timestamp_ = other.timestamp_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              stockSymbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              currentPrice_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              previousPrice_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 41: {
              changePercent_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 48: {
              isSignificantChange_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              changeDirection_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              recommendation_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              timestamp_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object stockSymbol_ = "";
    /**
     * <code>string stock_symbol = 2;</code>
     * @return The stockSymbol.
     */
    public java.lang.String getStockSymbol() {
      java.lang.Object ref = stockSymbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stockSymbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stock_symbol = 2;</code>
     * @return The bytes for stockSymbol.
     */
    public com.google.protobuf.ByteString
        getStockSymbolBytes() {
      java.lang.Object ref = stockSymbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stockSymbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stock_symbol = 2;</code>
     * @param value The stockSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setStockSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stockSymbol_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string stock_symbol = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStockSymbol() {
      stockSymbol_ = getDefaultInstance().getStockSymbol();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string stock_symbol = 2;</code>
     * @param value The bytes for stockSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setStockSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stockSymbol_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private double currentPrice_ ;
    /**
     * <code>double current_price = 3;</code>
     * @return The currentPrice.
     */
    @java.lang.Override
    public double getCurrentPrice() {
      return currentPrice_;
    }
    /**
     * <code>double current_price = 3;</code>
     * @param value The currentPrice to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentPrice(double value) {
      
      currentPrice_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double current_price = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentPrice() {
      bitField0_ = (bitField0_ & ~0x00000004);
      currentPrice_ = 0D;
      onChanged();
      return this;
    }

    private double previousPrice_ ;
    /**
     * <code>double previous_price = 4;</code>
     * @return The previousPrice.
     */
    @java.lang.Override
    public double getPreviousPrice() {
      return previousPrice_;
    }
    /**
     * <code>double previous_price = 4;</code>
     * @param value The previousPrice to set.
     * @return This builder for chaining.
     */
    public Builder setPreviousPrice(double value) {
      
      previousPrice_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double previous_price = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPreviousPrice() {
      bitField0_ = (bitField0_ & ~0x00000008);
      previousPrice_ = 0D;
      onChanged();
      return this;
    }

    private double changePercent_ ;
    /**
     * <code>double change_percent = 5;</code>
     * @return The changePercent.
     */
    @java.lang.Override
    public double getChangePercent() {
      return changePercent_;
    }
    /**
     * <code>double change_percent = 5;</code>
     * @param value The changePercent to set.
     * @return This builder for chaining.
     */
    public Builder setChangePercent(double value) {
      
      changePercent_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double change_percent = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearChangePercent() {
      bitField0_ = (bitField0_ & ~0x00000010);
      changePercent_ = 0D;
      onChanged();
      return this;
    }

    private boolean isSignificantChange_ ;
    /**
     * <code>bool is_significant_change = 6;</code>
     * @return The isSignificantChange.
     */
    @java.lang.Override
    public boolean getIsSignificantChange() {
      return isSignificantChange_;
    }
    /**
     * <code>bool is_significant_change = 6;</code>
     * @param value The isSignificantChange to set.
     * @return This builder for chaining.
     */
    public Builder setIsSignificantChange(boolean value) {
      
      isSignificantChange_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_significant_change = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSignificantChange() {
      bitField0_ = (bitField0_ & ~0x00000020);
      isSignificantChange_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object changeDirection_ = "";
    /**
     * <code>string change_direction = 7;</code>
     * @return The changeDirection.
     */
    public java.lang.String getChangeDirection() {
      java.lang.Object ref = changeDirection_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        changeDirection_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string change_direction = 7;</code>
     * @return The bytes for changeDirection.
     */
    public com.google.protobuf.ByteString
        getChangeDirectionBytes() {
      java.lang.Object ref = changeDirection_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        changeDirection_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string change_direction = 7;</code>
     * @param value The changeDirection to set.
     * @return This builder for chaining.
     */
    public Builder setChangeDirection(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      changeDirection_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string change_direction = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearChangeDirection() {
      changeDirection_ = getDefaultInstance().getChangeDirection();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string change_direction = 7;</code>
     * @param value The bytes for changeDirection to set.
     * @return This builder for chaining.
     */
    public Builder setChangeDirectionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      changeDirection_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object recommendation_ = "";
    /**
     * <code>string recommendation = 8;</code>
     * @return The recommendation.
     */
    public java.lang.String getRecommendation() {
      java.lang.Object ref = recommendation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recommendation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string recommendation = 8;</code>
     * @return The bytes for recommendation.
     */
    public com.google.protobuf.ByteString
        getRecommendationBytes() {
      java.lang.Object ref = recommendation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recommendation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string recommendation = 8;</code>
     * @param value The recommendation to set.
     * @return This builder for chaining.
     */
    public Builder setRecommendation(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      recommendation_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string recommendation = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecommendation() {
      recommendation_ = getDefaultInstance().getRecommendation();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string recommendation = 8;</code>
     * @param value The bytes for recommendation to set.
     * @return This builder for chaining.
     */
    public Builder setRecommendationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      recommendation_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object timestamp_ = "";
    /**
     * <pre>
     * 使用ISO 8601格式字符串
     * </pre>
     *
     * <code>string timestamp = 9;</code>
     * @return The timestamp.
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 使用ISO 8601格式字符串
     * </pre>
     *
     * <code>string timestamp = 9;</code>
     * @return The bytes for timestamp.
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 使用ISO 8601格式字符串
     * </pre>
     *
     * <code>string timestamp = 9;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      timestamp_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 使用ISO 8601格式字符串
     * </pre>
     *
     * <code>string timestamp = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      timestamp_ = getDefaultInstance().getTimestamp();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 使用ISO 8601格式字符串
     * </pre>
     *
     * <code>string timestamp = 9;</code>
     * @param value The bytes for timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      timestamp_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.skyeai.jarvis.PriceChangeInfoProto)
  }

  // @@protoc_insertion_point(class_scope:com.skyeai.jarvis.PriceChangeInfoProto)
  private static final com.skyeai.jarvis.protobuf.PriceChangeInfoProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.skyeai.jarvis.protobuf.PriceChangeInfoProto();
  }

  public static com.skyeai.jarvis.protobuf.PriceChangeInfoProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PriceChangeInfoProto>
      PARSER = new com.google.protobuf.AbstractParser<PriceChangeInfoProto>() {
    @java.lang.Override
    public PriceChangeInfoProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PriceChangeInfoProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PriceChangeInfoProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.skyeai.jarvis.protobuf.PriceChangeInfoProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

