// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

public interface SaveStockPriceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skyeai.jarvis.SaveStockPriceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.skyeai.jarvis.StockPriceProto stock_price = 1;</code>
   * @return Whether the stockPrice field is set.
   */
  boolean hasStockPrice();
  /**
   * <code>.com.skyeai.jarvis.StockPriceProto stock_price = 1;</code>
   * @return The stockPrice.
   */
  com.skyeai.jarvis.protobuf.StockPriceProto getStockPrice();
  /**
   * <code>.com.skyeai.jarvis.StockPriceProto stock_price = 1;</code>
   */
  com.skyeai.jarvis.protobuf.StockPriceProtoOrBuilder getStockPriceOrBuilder();
}
