// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

/**
 * <pre>
 * 保存日程事件响应
 * </pre>
 *
 * Protobuf type {@code com.skyeai.jarvis.SaveScheduleEventResponse}
 */
public final class SaveScheduleEventResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.skyeai.jarvis.SaveScheduleEventResponse)
    SaveScheduleEventResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SaveScheduleEventResponse.newBuilder() to construct.
  private SaveScheduleEventResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SaveScheduleEventResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SaveScheduleEventResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_SaveScheduleEventResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_SaveScheduleEventResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.skyeai.jarvis.protobuf.SaveScheduleEventResponse.class, com.skyeai.jarvis.protobuf.SaveScheduleEventResponse.Builder.class);
  }

  public static final int SCHEDULE_EVENT_FIELD_NUMBER = 1;
  private com.skyeai.jarvis.protobuf.ScheduleEventProto scheduleEvent_;
  /**
   * <code>.com.skyeai.jarvis.ScheduleEventProto schedule_event = 1;</code>
   * @return Whether the scheduleEvent field is set.
   */
  @java.lang.Override
  public boolean hasScheduleEvent() {
    return scheduleEvent_ != null;
  }
  /**
   * <code>.com.skyeai.jarvis.ScheduleEventProto schedule_event = 1;</code>
   * @return The scheduleEvent.
   */
  @java.lang.Override
  public com.skyeai.jarvis.protobuf.ScheduleEventProto getScheduleEvent() {
    return scheduleEvent_ == null ? com.skyeai.jarvis.protobuf.ScheduleEventProto.getDefaultInstance() : scheduleEvent_;
  }
  /**
   * <code>.com.skyeai.jarvis.ScheduleEventProto schedule_event = 1;</code>
   */
  @java.lang.Override
  public com.skyeai.jarvis.protobuf.ScheduleEventProtoOrBuilder getScheduleEventOrBuilder() {
    return scheduleEvent_ == null ? com.skyeai.jarvis.protobuf.ScheduleEventProto.getDefaultInstance() : scheduleEvent_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (scheduleEvent_ != null) {
      output.writeMessage(1, getScheduleEvent());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (scheduleEvent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getScheduleEvent());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.skyeai.jarvis.protobuf.SaveScheduleEventResponse)) {
      return super.equals(obj);
    }
    com.skyeai.jarvis.protobuf.SaveScheduleEventResponse other = (com.skyeai.jarvis.protobuf.SaveScheduleEventResponse) obj;

    if (hasScheduleEvent() != other.hasScheduleEvent()) return false;
    if (hasScheduleEvent()) {
      if (!getScheduleEvent()
          .equals(other.getScheduleEvent())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasScheduleEvent()) {
      hash = (37 * hash) + SCHEDULE_EVENT_FIELD_NUMBER;
      hash = (53 * hash) + getScheduleEvent().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.skyeai.jarvis.protobuf.SaveScheduleEventResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skyeai.jarvis.protobuf.SaveScheduleEventResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.SaveScheduleEventResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skyeai.jarvis.protobuf.SaveScheduleEventResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.SaveScheduleEventResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skyeai.jarvis.protobuf.SaveScheduleEventResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.SaveScheduleEventResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.skyeai.jarvis.protobuf.SaveScheduleEventResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.SaveScheduleEventResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.skyeai.jarvis.protobuf.SaveScheduleEventResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.SaveScheduleEventResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.skyeai.jarvis.protobuf.SaveScheduleEventResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.skyeai.jarvis.protobuf.SaveScheduleEventResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 保存日程事件响应
   * </pre>
   *
   * Protobuf type {@code com.skyeai.jarvis.SaveScheduleEventResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.skyeai.jarvis.SaveScheduleEventResponse)
      com.skyeai.jarvis.protobuf.SaveScheduleEventResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_SaveScheduleEventResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_SaveScheduleEventResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skyeai.jarvis.protobuf.SaveScheduleEventResponse.class, com.skyeai.jarvis.protobuf.SaveScheduleEventResponse.Builder.class);
    }

    // Construct using com.skyeai.jarvis.protobuf.SaveScheduleEventResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      scheduleEvent_ = null;
      if (scheduleEventBuilder_ != null) {
        scheduleEventBuilder_.dispose();
        scheduleEventBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_SaveScheduleEventResponse_descriptor;
    }

    @java.lang.Override
    public com.skyeai.jarvis.protobuf.SaveScheduleEventResponse getDefaultInstanceForType() {
      return com.skyeai.jarvis.protobuf.SaveScheduleEventResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.skyeai.jarvis.protobuf.SaveScheduleEventResponse build() {
      com.skyeai.jarvis.protobuf.SaveScheduleEventResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.skyeai.jarvis.protobuf.SaveScheduleEventResponse buildPartial() {
      com.skyeai.jarvis.protobuf.SaveScheduleEventResponse result = new com.skyeai.jarvis.protobuf.SaveScheduleEventResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.skyeai.jarvis.protobuf.SaveScheduleEventResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.scheduleEvent_ = scheduleEventBuilder_ == null
            ? scheduleEvent_
            : scheduleEventBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.skyeai.jarvis.protobuf.SaveScheduleEventResponse) {
        return mergeFrom((com.skyeai.jarvis.protobuf.SaveScheduleEventResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.skyeai.jarvis.protobuf.SaveScheduleEventResponse other) {
      if (other == com.skyeai.jarvis.protobuf.SaveScheduleEventResponse.getDefaultInstance()) return this;
      if (other.hasScheduleEvent()) {
        mergeScheduleEvent(other.getScheduleEvent());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getScheduleEventFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.skyeai.jarvis.protobuf.ScheduleEventProto scheduleEvent_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.skyeai.jarvis.protobuf.ScheduleEventProto, com.skyeai.jarvis.protobuf.ScheduleEventProto.Builder, com.skyeai.jarvis.protobuf.ScheduleEventProtoOrBuilder> scheduleEventBuilder_;
    /**
     * <code>.com.skyeai.jarvis.ScheduleEventProto schedule_event = 1;</code>
     * @return Whether the scheduleEvent field is set.
     */
    public boolean hasScheduleEvent() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.skyeai.jarvis.ScheduleEventProto schedule_event = 1;</code>
     * @return The scheduleEvent.
     */
    public com.skyeai.jarvis.protobuf.ScheduleEventProto getScheduleEvent() {
      if (scheduleEventBuilder_ == null) {
        return scheduleEvent_ == null ? com.skyeai.jarvis.protobuf.ScheduleEventProto.getDefaultInstance() : scheduleEvent_;
      } else {
        return scheduleEventBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.skyeai.jarvis.ScheduleEventProto schedule_event = 1;</code>
     */
    public Builder setScheduleEvent(com.skyeai.jarvis.protobuf.ScheduleEventProto value) {
      if (scheduleEventBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        scheduleEvent_ = value;
      } else {
        scheduleEventBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.skyeai.jarvis.ScheduleEventProto schedule_event = 1;</code>
     */
    public Builder setScheduleEvent(
        com.skyeai.jarvis.protobuf.ScheduleEventProto.Builder builderForValue) {
      if (scheduleEventBuilder_ == null) {
        scheduleEvent_ = builderForValue.build();
      } else {
        scheduleEventBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.skyeai.jarvis.ScheduleEventProto schedule_event = 1;</code>
     */
    public Builder mergeScheduleEvent(com.skyeai.jarvis.protobuf.ScheduleEventProto value) {
      if (scheduleEventBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          scheduleEvent_ != null &&
          scheduleEvent_ != com.skyeai.jarvis.protobuf.ScheduleEventProto.getDefaultInstance()) {
          getScheduleEventBuilder().mergeFrom(value);
        } else {
          scheduleEvent_ = value;
        }
      } else {
        scheduleEventBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.skyeai.jarvis.ScheduleEventProto schedule_event = 1;</code>
     */
    public Builder clearScheduleEvent() {
      bitField0_ = (bitField0_ & ~0x00000001);
      scheduleEvent_ = null;
      if (scheduleEventBuilder_ != null) {
        scheduleEventBuilder_.dispose();
        scheduleEventBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.skyeai.jarvis.ScheduleEventProto schedule_event = 1;</code>
     */
    public com.skyeai.jarvis.protobuf.ScheduleEventProto.Builder getScheduleEventBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getScheduleEventFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.skyeai.jarvis.ScheduleEventProto schedule_event = 1;</code>
     */
    public com.skyeai.jarvis.protobuf.ScheduleEventProtoOrBuilder getScheduleEventOrBuilder() {
      if (scheduleEventBuilder_ != null) {
        return scheduleEventBuilder_.getMessageOrBuilder();
      } else {
        return scheduleEvent_ == null ?
            com.skyeai.jarvis.protobuf.ScheduleEventProto.getDefaultInstance() : scheduleEvent_;
      }
    }
    /**
     * <code>.com.skyeai.jarvis.ScheduleEventProto schedule_event = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.skyeai.jarvis.protobuf.ScheduleEventProto, com.skyeai.jarvis.protobuf.ScheduleEventProto.Builder, com.skyeai.jarvis.protobuf.ScheduleEventProtoOrBuilder> 
        getScheduleEventFieldBuilder() {
      if (scheduleEventBuilder_ == null) {
        scheduleEventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.skyeai.jarvis.protobuf.ScheduleEventProto, com.skyeai.jarvis.protobuf.ScheduleEventProto.Builder, com.skyeai.jarvis.protobuf.ScheduleEventProtoOrBuilder>(
                getScheduleEvent(),
                getParentForChildren(),
                isClean());
        scheduleEvent_ = null;
      }
      return scheduleEventBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.skyeai.jarvis.SaveScheduleEventResponse)
  }

  // @@protoc_insertion_point(class_scope:com.skyeai.jarvis.SaveScheduleEventResponse)
  private static final com.skyeai.jarvis.protobuf.SaveScheduleEventResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.skyeai.jarvis.protobuf.SaveScheduleEventResponse();
  }

  public static com.skyeai.jarvis.protobuf.SaveScheduleEventResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SaveScheduleEventResponse>
      PARSER = new com.google.protobuf.AbstractParser<SaveScheduleEventResponse>() {
    @java.lang.Override
    public SaveScheduleEventResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SaveScheduleEventResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SaveScheduleEventResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.skyeai.jarvis.protobuf.SaveScheduleEventResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

