// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

public interface ChatHistoryProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skyeai.jarvis.ChatHistoryProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string role = 4;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <code>string role = 4;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <pre>
   * 使用ISO 8601格式字符串
   * </pre>
   *
   * <code>string created_at = 5;</code>
   * @return The createdAt.
   */
  java.lang.String getCreatedAt();
  /**
   * <pre>
   * 使用ISO 8601格式字符串
   * </pre>
   *
   * <code>string created_at = 5;</code>
   * @return The bytes for createdAt.
   */
  com.google.protobuf.ByteString
      getCreatedAtBytes();

  /**
   * <code>string session_id = 6;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 6;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>string content_type = 7;</code>
   * @return The contentType.
   */
  java.lang.String getContentType();
  /**
   * <code>string content_type = 7;</code>
   * @return The bytes for contentType.
   */
  com.google.protobuf.ByteString
      getContentTypeBytes();

  /**
   * <code>string media_url = 8;</code>
   * @return The mediaUrl.
   */
  java.lang.String getMediaUrl();
  /**
   * <code>string media_url = 8;</code>
   * @return The bytes for mediaUrl.
   */
  com.google.protobuf.ByteString
      getMediaUrlBytes();

  /**
   * <code>string metadata = 9;</code>
   * @return The metadata.
   */
  java.lang.String getMetadata();
  /**
   * <code>string metadata = 9;</code>
   * @return The bytes for metadata.
   */
  com.google.protobuf.ByteString
      getMetadataBytes();
}
