// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

public interface CleanExpiredChatHistoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skyeai.jarvis.CleanExpiredChatHistoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>int32 deletedCount = 2;</code>
   * @return The deletedCount.
   */
  int getDeletedCount();
}
