// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

public interface CleanExpiredChatHistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skyeai.jarvis.CleanExpiredChatHistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 days = 1;</code>
   * @return The days.
   */
  int getDays();
}
