// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

public interface DeleteScheduleEventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skyeai.jarvis.DeleteScheduleEventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();
}
