// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

public interface GetAllActiveScheduleEventsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skyeai.jarvis.GetAllActiveScheduleEventsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.skyeai.jarvis.ScheduleEventProto schedule_events = 1;</code>
   */
  java.util.List<com.skyeai.jarvis.protobuf.ScheduleEventProto> 
      getScheduleEventsList();
  /**
   * <code>repeated .com.skyeai.jarvis.ScheduleEventProto schedule_events = 1;</code>
   */
  com.skyeai.jarvis.protobuf.ScheduleEventProto getScheduleEvents(int index);
  /**
   * <code>repeated .com.skyeai.jarvis.ScheduleEventProto schedule_events = 1;</code>
   */
  int getScheduleEventsCount();
  /**
   * <code>repeated .com.skyeai.jarvis.ScheduleEventProto schedule_events = 1;</code>
   */
  java.util.List<? extends com.skyeai.jarvis.protobuf.ScheduleEventProtoOrBuilder> 
      getScheduleEventsOrBuilderList();
  /**
   * <code>repeated .com.skyeai.jarvis.ScheduleEventProto schedule_events = 1;</code>
   */
  com.skyeai.jarvis.protobuf.ScheduleEventProtoOrBuilder getScheduleEventsOrBuilder(
      int index);
}
