// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

public interface GetRecentPriceChangeInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skyeai.jarvis.GetRecentPriceChangeInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.skyeai.jarvis.PriceChangeInfoProto price_change_infos = 1;</code>
   */
  java.util.List<com.skyeai.jarvis.protobuf.PriceChangeInfoProto> 
      getPriceChangeInfosList();
  /**
   * <code>repeated .com.skyeai.jarvis.PriceChangeInfoProto price_change_infos = 1;</code>
   */
  com.skyeai.jarvis.protobuf.PriceChangeInfoProto getPriceChangeInfos(int index);
  /**
   * <code>repeated .com.skyeai.jarvis.PriceChangeInfoProto price_change_infos = 1;</code>
   */
  int getPriceChangeInfosCount();
  /**
   * <code>repeated .com.skyeai.jarvis.PriceChangeInfoProto price_change_infos = 1;</code>
   */
  java.util.List<? extends com.skyeai.jarvis.protobuf.PriceChangeInfoProtoOrBuilder> 
      getPriceChangeInfosOrBuilderList();
  /**
   * <code>repeated .com.skyeai.jarvis.PriceChangeInfoProto price_change_infos = 1;</code>
   */
  com.skyeai.jarvis.protobuf.PriceChangeInfoProtoOrBuilder getPriceChangeInfosOrBuilder(
      int index);
}
