// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

public interface GetRecentStockPriceBySymbolRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skyeai.jarvis.GetRecentStockPriceBySymbolRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stock_symbol = 1;</code>
   * @return The stockSymbol.
   */
  java.lang.String getStockSymbol();
  /**
   * <code>string stock_symbol = 1;</code>
   * @return The bytes for stockSymbol.
   */
  com.google.protobuf.ByteString
      getStockSymbolBytes();
}
