// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

public interface GetUserPreferencesByTypeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skyeai.jarvis.GetUserPreferencesByTypeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string preference_type = 2;</code>
   * @return The preferenceType.
   */
  java.lang.String getPreferenceType();
  /**
   * <code>string preference_type = 2;</code>
   * @return The bytes for preferenceType.
   */
  com.google.protobuf.ByteString
      getPreferenceTypeBytes();
}
