// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

public interface SaveScheduleEventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skyeai.jarvis.SaveScheduleEventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.skyeai.jarvis.ScheduleEventProto schedule_event = 1;</code>
   * @return Whether the scheduleEvent field is set.
   */
  boolean hasScheduleEvent();
  /**
   * <code>.com.skyeai.jarvis.ScheduleEventProto schedule_event = 1;</code>
   * @return The scheduleEvent.
   */
  com.skyeai.jarvis.protobuf.ScheduleEventProto getScheduleEvent();
  /**
   * <code>.com.skyeai.jarvis.ScheduleEventProto schedule_event = 1;</code>
   */
  com.skyeai.jarvis.protobuf.ScheduleEventProtoOrBuilder getScheduleEventOrBuilder();
}
