// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

/**
 * <pre>
 * 保存价格变动信息响应
 * </pre>
 *
 * Protobuf type {@code com.skyeai.jarvis.SavePriceChangeInfoResponse}
 */
public final class SavePriceChangeInfoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.skyeai.jarvis.SavePriceChangeInfoResponse)
    SavePriceChangeInfoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SavePriceChangeInfoResponse.newBuilder() to construct.
  private SavePriceChangeInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SavePriceChangeInfoResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SavePriceChangeInfoResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_SavePriceChangeInfoResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_SavePriceChangeInfoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse.class, com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse.Builder.class);
  }

  public static final int PRICE_CHANGE_INFO_FIELD_NUMBER = 1;
  private com.skyeai.jarvis.protobuf.PriceChangeInfoProto priceChangeInfo_;
  /**
   * <code>.com.skyeai.jarvis.PriceChangeInfoProto price_change_info = 1;</code>
   * @return Whether the priceChangeInfo field is set.
   */
  @java.lang.Override
  public boolean hasPriceChangeInfo() {
    return priceChangeInfo_ != null;
  }
  /**
   * <code>.com.skyeai.jarvis.PriceChangeInfoProto price_change_info = 1;</code>
   * @return The priceChangeInfo.
   */
  @java.lang.Override
  public com.skyeai.jarvis.protobuf.PriceChangeInfoProto getPriceChangeInfo() {
    return priceChangeInfo_ == null ? com.skyeai.jarvis.protobuf.PriceChangeInfoProto.getDefaultInstance() : priceChangeInfo_;
  }
  /**
   * <code>.com.skyeai.jarvis.PriceChangeInfoProto price_change_info = 1;</code>
   */
  @java.lang.Override
  public com.skyeai.jarvis.protobuf.PriceChangeInfoProtoOrBuilder getPriceChangeInfoOrBuilder() {
    return priceChangeInfo_ == null ? com.skyeai.jarvis.protobuf.PriceChangeInfoProto.getDefaultInstance() : priceChangeInfo_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (priceChangeInfo_ != null) {
      output.writeMessage(1, getPriceChangeInfo());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (priceChangeInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPriceChangeInfo());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse)) {
      return super.equals(obj);
    }
    com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse other = (com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse) obj;

    if (hasPriceChangeInfo() != other.hasPriceChangeInfo()) return false;
    if (hasPriceChangeInfo()) {
      if (!getPriceChangeInfo()
          .equals(other.getPriceChangeInfo())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPriceChangeInfo()) {
      hash = (37 * hash) + PRICE_CHANGE_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getPriceChangeInfo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 保存价格变动信息响应
   * </pre>
   *
   * Protobuf type {@code com.skyeai.jarvis.SavePriceChangeInfoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.skyeai.jarvis.SavePriceChangeInfoResponse)
      com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_SavePriceChangeInfoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_SavePriceChangeInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse.class, com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse.Builder.class);
    }

    // Construct using com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      priceChangeInfo_ = null;
      if (priceChangeInfoBuilder_ != null) {
        priceChangeInfoBuilder_.dispose();
        priceChangeInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_SavePriceChangeInfoResponse_descriptor;
    }

    @java.lang.Override
    public com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse getDefaultInstanceForType() {
      return com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse build() {
      com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse buildPartial() {
      com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse result = new com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.priceChangeInfo_ = priceChangeInfoBuilder_ == null
            ? priceChangeInfo_
            : priceChangeInfoBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse) {
        return mergeFrom((com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse other) {
      if (other == com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse.getDefaultInstance()) return this;
      if (other.hasPriceChangeInfo()) {
        mergePriceChangeInfo(other.getPriceChangeInfo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getPriceChangeInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.skyeai.jarvis.protobuf.PriceChangeInfoProto priceChangeInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.skyeai.jarvis.protobuf.PriceChangeInfoProto, com.skyeai.jarvis.protobuf.PriceChangeInfoProto.Builder, com.skyeai.jarvis.protobuf.PriceChangeInfoProtoOrBuilder> priceChangeInfoBuilder_;
    /**
     * <code>.com.skyeai.jarvis.PriceChangeInfoProto price_change_info = 1;</code>
     * @return Whether the priceChangeInfo field is set.
     */
    public boolean hasPriceChangeInfo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.skyeai.jarvis.PriceChangeInfoProto price_change_info = 1;</code>
     * @return The priceChangeInfo.
     */
    public com.skyeai.jarvis.protobuf.PriceChangeInfoProto getPriceChangeInfo() {
      if (priceChangeInfoBuilder_ == null) {
        return priceChangeInfo_ == null ? com.skyeai.jarvis.protobuf.PriceChangeInfoProto.getDefaultInstance() : priceChangeInfo_;
      } else {
        return priceChangeInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.skyeai.jarvis.PriceChangeInfoProto price_change_info = 1;</code>
     */
    public Builder setPriceChangeInfo(com.skyeai.jarvis.protobuf.PriceChangeInfoProto value) {
      if (priceChangeInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        priceChangeInfo_ = value;
      } else {
        priceChangeInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.skyeai.jarvis.PriceChangeInfoProto price_change_info = 1;</code>
     */
    public Builder setPriceChangeInfo(
        com.skyeai.jarvis.protobuf.PriceChangeInfoProto.Builder builderForValue) {
      if (priceChangeInfoBuilder_ == null) {
        priceChangeInfo_ = builderForValue.build();
      } else {
        priceChangeInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.skyeai.jarvis.PriceChangeInfoProto price_change_info = 1;</code>
     */
    public Builder mergePriceChangeInfo(com.skyeai.jarvis.protobuf.PriceChangeInfoProto value) {
      if (priceChangeInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          priceChangeInfo_ != null &&
          priceChangeInfo_ != com.skyeai.jarvis.protobuf.PriceChangeInfoProto.getDefaultInstance()) {
          getPriceChangeInfoBuilder().mergeFrom(value);
        } else {
          priceChangeInfo_ = value;
        }
      } else {
        priceChangeInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.skyeai.jarvis.PriceChangeInfoProto price_change_info = 1;</code>
     */
    public Builder clearPriceChangeInfo() {
      bitField0_ = (bitField0_ & ~0x00000001);
      priceChangeInfo_ = null;
      if (priceChangeInfoBuilder_ != null) {
        priceChangeInfoBuilder_.dispose();
        priceChangeInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.skyeai.jarvis.PriceChangeInfoProto price_change_info = 1;</code>
     */
    public com.skyeai.jarvis.protobuf.PriceChangeInfoProto.Builder getPriceChangeInfoBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getPriceChangeInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.skyeai.jarvis.PriceChangeInfoProto price_change_info = 1;</code>
     */
    public com.skyeai.jarvis.protobuf.PriceChangeInfoProtoOrBuilder getPriceChangeInfoOrBuilder() {
      if (priceChangeInfoBuilder_ != null) {
        return priceChangeInfoBuilder_.getMessageOrBuilder();
      } else {
        return priceChangeInfo_ == null ?
            com.skyeai.jarvis.protobuf.PriceChangeInfoProto.getDefaultInstance() : priceChangeInfo_;
      }
    }
    /**
     * <code>.com.skyeai.jarvis.PriceChangeInfoProto price_change_info = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.skyeai.jarvis.protobuf.PriceChangeInfoProto, com.skyeai.jarvis.protobuf.PriceChangeInfoProto.Builder, com.skyeai.jarvis.protobuf.PriceChangeInfoProtoOrBuilder> 
        getPriceChangeInfoFieldBuilder() {
      if (priceChangeInfoBuilder_ == null) {
        priceChangeInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.skyeai.jarvis.protobuf.PriceChangeInfoProto, com.skyeai.jarvis.protobuf.PriceChangeInfoProto.Builder, com.skyeai.jarvis.protobuf.PriceChangeInfoProtoOrBuilder>(
                getPriceChangeInfo(),
                getParentForChildren(),
                isClean());
        priceChangeInfo_ = null;
      }
      return priceChangeInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.skyeai.jarvis.SavePriceChangeInfoResponse)
  }

  // @@protoc_insertion_point(class_scope:com.skyeai.jarvis.SavePriceChangeInfoResponse)
  private static final com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse();
  }

  public static com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SavePriceChangeInfoResponse>
      PARSER = new com.google.protobuf.AbstractParser<SavePriceChangeInfoResponse>() {
    @java.lang.Override
    public SavePriceChangeInfoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SavePriceChangeInfoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SavePriceChangeInfoResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.skyeai.jarvis.protobuf.SavePriceChangeInfoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

