// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

/**
 * <pre>
 * 保存用户偏好响应
 * </pre>
 *
 * Protobuf type {@code com.skyeai.jarvis.SaveUserPreferenceResponse}
 */
public final class SaveUserPreferenceResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.skyeai.jarvis.SaveUserPreferenceResponse)
    SaveUserPreferenceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SaveUserPreferenceResponse.newBuilder() to construct.
  private SaveUserPreferenceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SaveUserPreferenceResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SaveUserPreferenceResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_SaveUserPreferenceResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_SaveUserPreferenceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse.class, com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse.Builder.class);
  }

  public static final int USER_PREFERENCE_FIELD_NUMBER = 1;
  private com.skyeai.jarvis.protobuf.UserPreferenceProto userPreference_;
  /**
   * <code>.com.skyeai.jarvis.UserPreferenceProto user_preference = 1;</code>
   * @return Whether the userPreference field is set.
   */
  @java.lang.Override
  public boolean hasUserPreference() {
    return userPreference_ != null;
  }
  /**
   * <code>.com.skyeai.jarvis.UserPreferenceProto user_preference = 1;</code>
   * @return The userPreference.
   */
  @java.lang.Override
  public com.skyeai.jarvis.protobuf.UserPreferenceProto getUserPreference() {
    return userPreference_ == null ? com.skyeai.jarvis.protobuf.UserPreferenceProto.getDefaultInstance() : userPreference_;
  }
  /**
   * <code>.com.skyeai.jarvis.UserPreferenceProto user_preference = 1;</code>
   */
  @java.lang.Override
  public com.skyeai.jarvis.protobuf.UserPreferenceProtoOrBuilder getUserPreferenceOrBuilder() {
    return userPreference_ == null ? com.skyeai.jarvis.protobuf.UserPreferenceProto.getDefaultInstance() : userPreference_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userPreference_ != null) {
      output.writeMessage(1, getUserPreference());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userPreference_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUserPreference());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse)) {
      return super.equals(obj);
    }
    com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse other = (com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse) obj;

    if (hasUserPreference() != other.hasUserPreference()) return false;
    if (hasUserPreference()) {
      if (!getUserPreference()
          .equals(other.getUserPreference())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUserPreference()) {
      hash = (37 * hash) + USER_PREFERENCE_FIELD_NUMBER;
      hash = (53 * hash) + getUserPreference().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 保存用户偏好响应
   * </pre>
   *
   * Protobuf type {@code com.skyeai.jarvis.SaveUserPreferenceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.skyeai.jarvis.SaveUserPreferenceResponse)
      com.skyeai.jarvis.protobuf.SaveUserPreferenceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_SaveUserPreferenceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_SaveUserPreferenceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse.class, com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse.Builder.class);
    }

    // Construct using com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userPreference_ = null;
      if (userPreferenceBuilder_ != null) {
        userPreferenceBuilder_.dispose();
        userPreferenceBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.skyeai.jarvis.protobuf.DataServiceProto.internal_static_com_skyeai_jarvis_SaveUserPreferenceResponse_descriptor;
    }

    @java.lang.Override
    public com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse getDefaultInstanceForType() {
      return com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse build() {
      com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse buildPartial() {
      com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse result = new com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userPreference_ = userPreferenceBuilder_ == null
            ? userPreference_
            : userPreferenceBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse) {
        return mergeFrom((com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse other) {
      if (other == com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse.getDefaultInstance()) return this;
      if (other.hasUserPreference()) {
        mergeUserPreference(other.getUserPreference());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getUserPreferenceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.skyeai.jarvis.protobuf.UserPreferenceProto userPreference_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.skyeai.jarvis.protobuf.UserPreferenceProto, com.skyeai.jarvis.protobuf.UserPreferenceProto.Builder, com.skyeai.jarvis.protobuf.UserPreferenceProtoOrBuilder> userPreferenceBuilder_;
    /**
     * <code>.com.skyeai.jarvis.UserPreferenceProto user_preference = 1;</code>
     * @return Whether the userPreference field is set.
     */
    public boolean hasUserPreference() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.skyeai.jarvis.UserPreferenceProto user_preference = 1;</code>
     * @return The userPreference.
     */
    public com.skyeai.jarvis.protobuf.UserPreferenceProto getUserPreference() {
      if (userPreferenceBuilder_ == null) {
        return userPreference_ == null ? com.skyeai.jarvis.protobuf.UserPreferenceProto.getDefaultInstance() : userPreference_;
      } else {
        return userPreferenceBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.skyeai.jarvis.UserPreferenceProto user_preference = 1;</code>
     */
    public Builder setUserPreference(com.skyeai.jarvis.protobuf.UserPreferenceProto value) {
      if (userPreferenceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userPreference_ = value;
      } else {
        userPreferenceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.skyeai.jarvis.UserPreferenceProto user_preference = 1;</code>
     */
    public Builder setUserPreference(
        com.skyeai.jarvis.protobuf.UserPreferenceProto.Builder builderForValue) {
      if (userPreferenceBuilder_ == null) {
        userPreference_ = builderForValue.build();
      } else {
        userPreferenceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.skyeai.jarvis.UserPreferenceProto user_preference = 1;</code>
     */
    public Builder mergeUserPreference(com.skyeai.jarvis.protobuf.UserPreferenceProto value) {
      if (userPreferenceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          userPreference_ != null &&
          userPreference_ != com.skyeai.jarvis.protobuf.UserPreferenceProto.getDefaultInstance()) {
          getUserPreferenceBuilder().mergeFrom(value);
        } else {
          userPreference_ = value;
        }
      } else {
        userPreferenceBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.skyeai.jarvis.UserPreferenceProto user_preference = 1;</code>
     */
    public Builder clearUserPreference() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userPreference_ = null;
      if (userPreferenceBuilder_ != null) {
        userPreferenceBuilder_.dispose();
        userPreferenceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.skyeai.jarvis.UserPreferenceProto user_preference = 1;</code>
     */
    public com.skyeai.jarvis.protobuf.UserPreferenceProto.Builder getUserPreferenceBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getUserPreferenceFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.skyeai.jarvis.UserPreferenceProto user_preference = 1;</code>
     */
    public com.skyeai.jarvis.protobuf.UserPreferenceProtoOrBuilder getUserPreferenceOrBuilder() {
      if (userPreferenceBuilder_ != null) {
        return userPreferenceBuilder_.getMessageOrBuilder();
      } else {
        return userPreference_ == null ?
            com.skyeai.jarvis.protobuf.UserPreferenceProto.getDefaultInstance() : userPreference_;
      }
    }
    /**
     * <code>.com.skyeai.jarvis.UserPreferenceProto user_preference = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.skyeai.jarvis.protobuf.UserPreferenceProto, com.skyeai.jarvis.protobuf.UserPreferenceProto.Builder, com.skyeai.jarvis.protobuf.UserPreferenceProtoOrBuilder> 
        getUserPreferenceFieldBuilder() {
      if (userPreferenceBuilder_ == null) {
        userPreferenceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.skyeai.jarvis.protobuf.UserPreferenceProto, com.skyeai.jarvis.protobuf.UserPreferenceProto.Builder, com.skyeai.jarvis.protobuf.UserPreferenceProtoOrBuilder>(
                getUserPreference(),
                getParentForChildren(),
                isClean());
        userPreference_ = null;
      }
      return userPreferenceBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.skyeai.jarvis.SaveUserPreferenceResponse)
  }

  // @@protoc_insertion_point(class_scope:com.skyeai.jarvis.SaveUserPreferenceResponse)
  private static final com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse();
  }

  public static com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SaveUserPreferenceResponse>
      PARSER = new com.google.protobuf.AbstractParser<SaveUserPreferenceResponse>() {
    @java.lang.Override
    public SaveUserPreferenceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SaveUserPreferenceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SaveUserPreferenceResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.skyeai.jarvis.protobuf.SaveUserPreferenceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

