// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

public interface SearchSimilarChatHistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skyeai.jarvis.SearchSimilarChatHistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query = 1;</code>
   * @return The query.
   */
  java.lang.String getQuery();
  /**
   * <code>string query = 1;</code>
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString
      getQueryBytes();

  /**
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>int32 limit = 3;</code>
   * @return The limit.
   */
  int getLimit();
}
