// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_service.proto

package com.skyeai.jarvis.protobuf;

public interface SearchSimilarChatHistoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.skyeai.jarvis.SearchSimilarChatHistoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
   */
  java.util.List<com.skyeai.jarvis.protobuf.ChatHistoryProto> 
      getChatHistoriesList();
  /**
   * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
   */
  com.skyeai.jarvis.protobuf.ChatHistoryProto getChatHistories(int index);
  /**
   * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
   */
  int getChatHistoriesCount();
  /**
   * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
   */
  java.util.List<? extends com.skyeai.jarvis.protobuf.ChatHistoryProtoOrBuilder> 
      getChatHistoriesOrBuilderList();
  /**
   * <code>repeated .com.skyeai.jarvis.ChatHistoryProto chat_histories = 1;</code>
   */
  com.skyeai.jarvis.protobuf.ChatHistoryProtoOrBuilder getChatHistoriesOrBuilder(
      int index);
}
